injection_method: clean
attack_tool:
  - all
  # - agg
  # - non-agg

write_db: false # true,false

llms:
  # - claude-3-5-sonnet-20240620
  # - ollama/qwen2:72b
  # - ollama/qwen2:7b
  # - ollama/gemma2:9b
  # - ollama/gemma2:27b
  # - ollama/llama3:70b
  # - ollama/llama3.1:70b
  # - ollama/mixtral:8x7b
  # - ollama/llama3:8b
  # - ollama/llama3.1:8b

  - deepseek-v4-flash
attack_types:
  - combined_attack


defense_type: dynamic_prompt_rewriting # delimiters_defense, direct_paraphrase_defense, instructional_prevention, dynamic_prompt_rewriting
suffix: deepseek_full
