injection_method: DPI_MP
attack_tool:
  - all
  # - agg
  # - non-agg

read_db: true # true,false

llms:
  # - claude-3-5-sonnet-20240620

  # - ollama/gemma2:27b
  # - ollama/llama3:70b
  # - ollama/llama3.1:70b
  # - ollama/llama3:8b

  # - ollama/qwen2:72b
  # - ollama/qwen2:7b
  # - ollama/gemma2:9b
  # - ollama/mixtral:8x7b
  # - ollama/llama3.1:8b


  - deepseek-v4-flash
attack_types:
  - combined_attack
  # - context_ignoring
  # - fake_completion
  # - escape_characters
  # - naive

suffix: deepseek_full
