"""Append-only JSONL execution traces and reproducible run manifests."""

from __future__ import annotations

import json
import os
import socket
from collections.abc import Iterator
from contextlib import contextmanager
from pathlib import Path
from typing import Any

from pydantic import BaseModel

from selfauditbench.core.models import (
    AuditAttempt,
    AuditRecord,
    BrokerDecision,
    RiskyBehaviorRecord,
    RunManifest,
    ScenarioResult,
)
from selfauditbench.storage.hashing import canonical_json, sha256_file, sha256_json

INTEGRITY_FILENAME = "integrity.json"
RUN_LOCK_FILENAME = ".active-run.lock"


class RunLeaseError(RuntimeError):
    """Another process owns the output directory for this run ID."""


class ArtifactStore:
    """Write one inspectable artifact directory per benchmark run."""

    def __init__(self, root: Path, run_id: str) -> None:
        self.run_dir = root / run_id
        self.run_dir.mkdir(parents=True, exist_ok=True)

    @contextmanager
    def run_lease(self) -> Iterator[None]:
        """Hold an OS-released exclusive lease while mutating one run directory."""

        lock_path = self.run_dir / RUN_LOCK_FILENAME
        handle = lock_path.open("a+b")
        try:
            _lock_run_file(handle)
        except OSError as exc:
            handle.close()
            owner = _read_lock_owner(lock_path)
            detail = f" Current owner: {owner}." if owner else ""
            raise RunLeaseError(
                f"run {self.run_dir.name!r} is already active; wait for the existing "
                f"process or use a distinct run ID/output directory.{detail}"
            ) from exc
        try:
            owner = {
                "hostname": socket.gethostname(),
                "pid": os.getpid(),
                "run_dir": str(self.run_dir.resolve()),
            }
            handle.seek(0)
            handle.truncate()
            handle.write(json.dumps(owner, sort_keys=True).encode("utf-8"))
            handle.flush()
            yield
        finally:
            _unlock_run_file(handle)
            handle.close()

    def reset_replay_outputs(self) -> None:
        """Remove only the files generated by a prior replay with this run ID."""

        for filename in (
            "events.jsonl",
            "audits.jsonl",
            "audit_attempts.jsonl",
            "decisions.jsonl",
            "results.jsonl",
            "agent_safety_events.jsonl",
            "metrics.json",
            "dataset.json",
            "manifest.json",
            "report.md",
            "supplementary_reliability.json",
            "supplementary_reliability.md",
            INTEGRITY_FILENAME,
        ):
            path = self.run_dir / filename
            if path.exists():
                path.unlink()

    def reset_closed_loop_outputs(self) -> None:
        """Remove files generated by a prior closed-loop run with this run ID."""

        self.reset_replay_outputs()
        for filename in (
            "recovery_turns.jsonl",
            "controller_feedback.jsonl",
            "action_executions.jsonl",
            "outcome_judgments.jsonl",
            "closed_loop_model_attempts.jsonl",
            "closed_loop_trajectories.jsonl",
            "closed_loop_summary.csv",
            "closed_loop_summary.md",
        ):
            path = self.run_dir / filename
            if path.exists():
                path.unlink()

    def append_jsonl(self, filename: str, record: BaseModel | dict[str, Any]) -> None:
        path = self.run_dir / filename
        value = record.model_dump(mode="json") if isinstance(record, BaseModel) else record
        with path.open("a", encoding="utf-8") as handle:
            handle.write(canonical_json(value) + "\n")

    def write_json(self, filename: str, value: BaseModel | dict[str, Any] | list[Any]) -> Path:
        path = self.run_dir / filename
        payload = value.model_dump(mode="json") if isinstance(value, BaseModel) else value
        path.write_text(canonical_json(payload) + "\n", encoding="utf-8")
        return path

    def write_text(self, filename: str, text: str) -> Path:
        path = self.run_dir / filename
        path.write_text(text, encoding="utf-8")
        return path

    def record_event(self, event: BaseModel) -> None:
        self.append_jsonl("events.jsonl", event)

    def record_audit(self, audit: AuditRecord) -> None:
        self.append_jsonl("audits.jsonl", audit)

    def record_audit_attempt(self, attempt: AuditAttempt) -> None:
        self.append_jsonl("audit_attempts.jsonl", attempt)

    def record_decision(self, decision: BrokerDecision) -> None:
        self.append_jsonl("decisions.jsonl", decision)

    def record_agent_safety_event(self, event: RiskyBehaviorRecord) -> None:
        self.append_jsonl("agent_safety_events.jsonl", event)

    def record_result(self, result: ScenarioResult) -> None:
        self.append_jsonl("results.jsonl", result)

    def write_manifest(self, manifest: RunManifest) -> Path:
        return self.write_json("manifest.json", manifest)

    def write_integrity_manifest(self) -> Path:
        return write_integrity_manifest(self.run_dir)


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8") as handle:
        return [json.loads(line) for line in handle if line.strip()]


def write_integrity_manifest(run_dir: Path) -> Path:
    """Freeze every emitted run artifact in a content-addressed manifest."""

    entries = _integrity_entries(run_dir)
    payload = {
        "schema_version": "1.0",
        "algorithm": "sha256",
        "entries": entries,
        "root_digest": sha256_json(entries),
    }
    path = run_dir / INTEGRITY_FILENAME
    path.write_text(canonical_json(payload) + "\n", encoding="utf-8")
    return path


def verify_integrity_manifest(run_dir: Path) -> dict[str, Any]:
    """Verify a frozen run without treating older unmanifested runs as corrupt."""

    path = run_dir / INTEGRITY_FILENAME
    if not path.exists():
        return {
            "status": "legacy_unverified",
            "verified": False,
            "errors": [f"missing {INTEGRITY_FILENAME}"],
        }
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        return {"status": "corrupt", "verified": False, "errors": [str(exc)]}
    expected = payload.get("entries")
    if not isinstance(expected, dict):
        return {
            "status": "corrupt",
            "verified": False,
            "errors": ["integrity entries must be a JSON object"],
        }
    errors: list[str] = []
    expected_root = payload.get("root_digest")
    if expected_root != sha256_json(expected):
        errors.append("integrity root digest does not match its entry map")
    actual = _integrity_entries(run_dir)
    expected_names = set(expected)
    actual_names = set(actual)
    for name in sorted(expected_names - actual_names):
        errors.append(f"missing artifact: {name}")
    for name in sorted(actual_names - expected_names):
        errors.append(f"unexpected artifact: {name}")
    for name in sorted(expected_names & actual_names):
        if expected[name] != actual[name]:
            errors.append(f"artifact mismatch: {name}")
    return {
        "status": "verified" if not errors else "corrupt",
        "verified": not errors,
        "root_digest": expected_root,
        "artifact_count": len(expected),
        "errors": errors,
    }


def _integrity_entries(run_dir: Path) -> dict[str, dict[str, int | str]]:
    entries: dict[str, dict[str, int | str]] = {}
    if not run_dir.exists():
        return entries
    for path in sorted(item for item in run_dir.rglob("*") if item.is_file()):
        relative = path.relative_to(run_dir).as_posix()
        if relative in {INTEGRITY_FILENAME, RUN_LOCK_FILENAME}:
            continue
        entry: dict[str, int | str] = {
            "sha256": sha256_file(path),
            "bytes": path.stat().st_size,
        }
        if path.suffix.lower() == ".jsonl":
            with path.open("r", encoding="utf-8") as handle:
                entry["records"] = sum(bool(line.strip()) for line in handle)
        entries[relative] = entry
    return entries


def _lock_run_file(handle: Any) -> None:
    if os.name == "nt":
        import msvcrt

        handle.seek(0, os.SEEK_END)
        if handle.tell() == 0:
            handle.write(b"\0")
            handle.flush()
        handle.seek(0)
        msvcrt.locking(handle.fileno(), msvcrt.LK_NBLCK, 1)
        return

    import fcntl

    fcntl.flock(handle.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)


def _unlock_run_file(handle: Any) -> None:
    if os.name == "nt":
        import msvcrt

        handle.seek(0)
        msvcrt.locking(handle.fileno(), msvcrt.LK_UNLCK, 1)
        return

    import fcntl

    fcntl.flock(handle.fileno(), fcntl.LOCK_UN)


def _read_lock_owner(path: Path) -> str:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return ""
    if not isinstance(value, dict):
        return ""
    return ", ".join(
        f"{key}={value[key]}" for key in ("hostname", "pid", "run_dir") if key in value
    )
